[package]
name = "aegistrate"
version = "0.1.0"
edition = "2021"
authors = ["developer-ramen <ramendev2009@gmail.com>"]
# rust-version â€” The minimal supported Rust version.
description = "Your Discord guild's aegis and magistrate! Yes, some people get that portmanteau."
readme = "README.md"
repository = "https://github.com/developer-ramen/aegistrate"
license = "MIT"
keywords = ["discord", "discord-bot", "moderation", "general-purpose"]

[dependencies]
anyhow = "1.0.71"
async-trait = "0.1.68"
derive_builder = "0.12.0"
dotenv = "0.15.0"
enum-iterator = "1.4.1"
env_logger = "0.10.0"
log = "0.4.17"
serenity = { version = "0.11.5", default-features = false, features = ["cache", "client", "gateway", "model", "rustls_backend"] }
tokio = { version = "1.28.1", features = ["full"] }
